// <auto-generated />
using FlightManagerSimulator.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace FlightManagerSimulator.DataLayer.DataModel.Migrations
{
    [DbContext(typeof(FlightManagerDbContext))]
    partial class FlightManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("FlightManagerSimulator.DataLayer.Models.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<double>("InFlyFuelConsumption");

                    b.Property<double>("InTakeOffFuelConsumption");

                    b.Property<string>("MaxSpeed");

                    b.Property<string>("Name");

                    b.Property<int>("PassengerCapacity");

                    b.HasKey("Id");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("FlightManagerSimulator.DataLayer.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("FlightManagerSimulator.DataLayer.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AircraftId");

                    b.Property<int>("Days");

                    b.Property<int?>("DepartureAirportId");

                    b.Property<int?>("DestinationAirportId");

                    b.Property<double>("Distance");

                    b.Property<double>("FuelNeeded");

                    b.Property<string>("Identifier");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("DepartureAirportId");

                    b.HasIndex("DestinationAirportId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlightManagerSimulator.DataLayer.Models.Flight", b =>
                {
                    b.HasOne("FlightManagerSimulator.DataLayer.Models.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId");

                    b.HasOne("FlightManagerSimulator.DataLayer.Models.Airport", "DepartureAirport")
                        .WithMany()
                        .HasForeignKey("DepartureAirportId");

                    b.HasOne("FlightManagerSimulator.DataLayer.Models.Airport", "DestinationAirport")
                        .WithMany()
                        .HasForeignKey("DestinationAirportId");
                });
#pragma warning restore 612, 618
        }
    }
}
